# Note: MIDI access is not auto-connected. Run:
# - sudo snap connect powertabeditor:alsa
# - sudo snap connect powertabeditor:jack1

name: powertabeditor
base: core20
version: '2.0.0-alpha15'
adopt-info: powertabeditor

grade: stable
confinement: strict

parts:
  powertabeditor:
    parse-info:
      - /root/parts/powertabeditor/install/usr/local/share/metainfo/powertabeditor.metainfo.xml
    plugin: cmake
    source: https://github.com/powertab/powertabeditor.git
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_FIND_ROOT_PATH="usr;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
    build-snaps:
      - kde-frameworks-5-qt-5-15-core20-sdk # For Qt and minizip
    build-packages:
      - libboost-dev
      - libboost-date-time-dev
      - libboost-iostreams-dev
      - rapidjson-dev
      - libasound2-dev
      - librtmidi-dev
      - libminizip-dev
      - doctest-dev
      - libpugixml-dev
    stage-packages:
      - libboost-date-time1.71.0
      - libboost-iostreams1.71.0
      - libasound2
      - libjack0
      - librtmidi4
      - libminizip1
      - libpugixml1v5

layout:
  # Bindings needed for ALSA, see https://forum.snapcraft.io/t/the-alsa-interface/7766/7
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/alsa:
    bind: $SNAP/etc/alsa
  # For the tuning dictionary (tunings.json)
  /usr/local/share:
    bind: $SNAP/usr/local/share

apps:
  powertabeditor:
    common-id: powertabeditor
    command: usr/local/bin/powertabeditor
    extensions:
      - kde-neon
    plugs:
      - alsa # For rtmidi's ALSA backend
      - audio-playback
      - home
      - network
      - jack1 # For rtmidi's JACK backend
