name: Build

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Apt Dependencies
      run: sudo apt update && sudo apt install ninja-build qtbase5-dev libboost-dev libboost-date-time-dev libboost-filesystem-dev libboost-iostreams-dev libboost-program-options-dev libboost-regex-dev rapidjson-dev libasound2-dev librtmidi-dev
    - name: Install Other Dependencies
      run: vcpkg install catch2 pugixml
    - name: Create Build Directory
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: Generate Project
      working-directory: ${{runner.workspace}}/build
      # We could use the -S and -B options, but we only have CMake 3.12 here.
      run: cmake ${GITHUB_WORKSPACE} -G Ninja -DCMAKE_TOOLCHAIN_FILE="${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake"
    - name: Build
      run: ninja -C ${{runner.workspace}}/build
    - name: Test
      run: ${{runner.workspace}}/build/bin/pte_tests
